### ISSUE TITLE
Fix copyright notes

### ISSUE THREAD

**Issue by johnshajiang** [Tencent/TencentKona-17#19]
修改腾讯自有文件的版本声明中的问题，比如年份之后缺少逗号。

腾讯自有文件的版权声明包含如下字样：
```
Copyright (C) 2023, THL A29 Limited, a Tencent company. All rights reserved.
```

在发邮件时，请在标题的开头处注明`[姓名+GitHubID+IssueID]`。
例如，`[江莎+johnshajiang+25]`

---
**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。

**Comment by k-azv** [comment]
已成功领取本issue

**Comment by iseri-nina** [comment]
我想问一下，部分腾讯自有文件的版权声明部分的尾部存在一行应该是有意为之的空行，是否属于需要修正的内容，谢谢
```java
/*
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 *  <- 这里
 */
```

**Comment by johnshajiang** [comment]
那个空行可有可无，但一般不认为那是一个问题，可以不作修改。

**Comment by johnshajiang** [comment]
@iseri-nina 
你是否已经签属了[Tencent Contributor License Agreement]？

[Tencent Contributor License Agreement]:
https://cla.opensource.tencent.com/

**Comment by johnshajiang** [comment]
> 请问这个协议是填好信息之后发邮件到[TencentCLA@tencent.com](mailto:TencentCLA@tencent.com)就行了吗？谢谢

请根据提示处理。

**Comment by johnshajiang** [comment]
> 除开这个问题之外版本声明部分似乎不存在其他问题了

其实下面这个写法就有问题，
`Copyright (C) 2021 THL A29 Limited, a Tencent company. All rights reserved.`
`2021`后面还需要一个逗号，即写为
`Copyright (C) 2021, THL A29 Limited, a Tencent company. All rights reserved.`。

**Comment by iseri-nina** [comment]
这也是让我很困惑的一点，这个项目中所有的
`Copyright (C) 20XX THL A29 Limited, a Tencent company. All rights reserved.`
都没有在年份之后加上逗号，而且腾讯其他的项目中也没有在年份之后加上逗号 ，我就以为这个就是要这样写的😂

十分感谢

**Comment by johnshajiang** [comment]
也不是所有的都没有加逗号，还是有一部分是加上了的。
当然，这是一个很容易被忽视的问题。

**Comment by johnshajiang** [comment]
在发邮件时，请在标题的开头处注明`[姓名+GitHubID+IssueID]`。
例如，`[江莎+johnshajiang+25]`

**Comment by johnshajiang** [comment]
认为PR #29 解决了这个issue。
