### ISSUE TITLE
Remove redundant spaces and lines

### ISSUE THREAD

**Issue by johnshajiang** [Tencent/TencentKona-17#20]
修改腾讯自有文件中出现的尾空格，冗余空行等问题。

腾讯自有文件的版权声明包含如下字样：
```
Copyright (C) 2023, THL A29 Limited, a Tencent company. All rights reserved.
```

在发邮件时，请在标题的开头处注明`[姓名+GitHubID+IssueID]`。
例如，`[江莎+johnshajiang+25]`

---
**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。

**Comment by heliang666s** [comment]
已成功领取本issue

**Comment by mck156** [comment]
已成功领取本issue

**Comment by johnshajiang** [comment]
我刚刚查看了下面的文档
https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D?tab=21oiuu&_t=1719895756715

@mck156 是不是你第一个抢到的？

**Comment by mck156** [comment]
@johnshajiang  嗯嗯。报名时原本有一个issue回复但报名表是空的，问负责人他说以报名表为准，就来了。

**Comment by heliang666s** [comment]
![图片](https://github.com/Tencent/TencentKona-17/assets/147408835/53b4f9bd-7059-49ac-8078-4ee0cb4e6ed7)
我这边显示我是第一个@johnshajiang

**Comment by mck156** [comment]
@heliang666s 
![报名](https://github.com/Tencent/TencentKona-17/assets/125785475/64304563-42ed-452c-8497-69fa06f82529)
我觉得只有说喊负责人来说啷个弄了，这个有点小尴尬

**Comment by mck156** [comment]
@heliang666s 感觉是腾讯文档的锅😂😂

**Comment by heliang666s** [comment]
确实，让负责人定夺吧

**Comment by johnshajiang** [comment]
我看到的信息如下：
<img width="714" src="https://github.com/Tencent/TencentKona-17/assets/20450620/aa644045-654e-43c4-b7cd-570c2358cf7d">

**Comment by johnshajiang** [comment]
@heliang666s 
你看到的信息和上面不一样？

**Comment by mck156** [comment]
@heliang666s 您好！兄弟（暂且称呼），刚刚找工作人员查找了，以下是其回复的结果：“这条issue，6.29已被饶智鸿同学领取（30日前已锁定了该报名单元格）何亮同学参与的是82行的issue，也是于今天中午1点多第一次进入研学基地文档并填写的报名”，请您再次查看一下表格并看看是否有误！如果有什么问题随时沟通及时处理，感谢恁的支持！

**Comment by johnshajiang** [comment]
@mck156 
你是否已经签属了[Tencent Contributor License Agreement]？

[Tencent Contributor License Agreement]:
https://cla.opensource.tencent.com/

**Comment by heliang666s** [comment]
@mck156 那你先做吧，我重新报名排队

**Comment by mck156** [comment]
@heliang666s 要的，谢谢你！！

**Comment by mck156** [comment]
@johnshajiang 签署了并发到了邮箱里面了

**Comment by mck156** [comment]
@johnshajiang 江莎老师，“Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.” 我想把 “lnc.,” 改成 “lnc,” 您看可以不 ？

**Comment by johnshajiang** [comment]
> “Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.” 我想把 “lnc.,” 改成 “lnc,” 您看可以不 ？

我们不要修改别的版本声明。

**Comment by mck156** [comment]
> > “Inc.， 51 Franklin St， Fifth Floor， Boston， MA 02110-1301 USA.” 我想把 “lnc.”， 改成 “lnc”， 您看可以不 ？
> 
> 我们不要修改别的版本声明。

那我就不更改它，我提交的文件没有更改，可以放心查看！

**Comment by johnshajiang** [comment]
在发邮件时，请在标题的开头处注明`[姓名+GitHubID+IssueID]`。
例如，`[江莎+johnshajiang+25]`

**Comment by mck156** [comment]
@johnshajiang 好！

**Comment by tencent-adm** [comment]
@heliang666s 同学你好，经判断为腾讯文档bug，你可以继续做issue，issue完成后，组委会也会同步发放激励，导师这边也给你提了修改意见，可以看看哟~

**Comment by johnshajiang** [comment]
认为PR #32 解决了这个issue。
