### ISSUE TITLE
macosx 1.0 解压后无法使用

### ISSUE THREAD

**Issue by onexuan** [Tencent/TencentKona-17#3]
TencentKona-17.0.0.b1-ea_jdk_macosx-x86_64.tar.gz 解压后无法使用

**Comment by shiyuexw** [comment]
麻烦描述下具体的错误。
另外，检查下文件的md5是否一致。

**Comment by onexuan** [comment]
> 麻烦描述下具体的错误。 另外，检查下文件的md5是否一致。

就是我下载这个压缩包后，解压后，无法进入文件夹，TencentKona-11解压就正常

**Comment by shiyuexw** [comment]
1. 窗口下可以鼠标右键 --》 查看内容  的方式打开，也可以直接在终端里打开；
2. 或者下载认证版本：https://github.com/Tencent/TencentKona-17/releases/download/TencentKona-17.0.0/TencentKona-17.0.0.b1-ea_jdk_macosx-x86_64_notarized.tar.gz

**Comment by onexuan** [comment]
> 1. 窗口下可以鼠标右键 --》 查看内容  的方式打开，也可以直接在终端里打开；
> 2. 或者下载认证版本：https://github.com/Tencent/TencentKona-17/releases/download/TencentKona-17.0.0/TencentKona-17.0.0.b1-ea_jdk_macosx-x86_64_notarized.tar.gz

这个正常了
