### ISSUE TITLE
Should update the supported platforms in README

### ISSUE THREAD

**Issue by johnshajiang** [Tencent/TencentKona-17#7]
The README contains the below line,
```
Tencent Kona JDK17 currently supports Linux/x86_64 and Linux/Aarch64 platform.
```
However, Kona 17 already releases builds for Windows and Mac platforms.
https://github.com/Tencent/TencentKona-17/releases

**Comment by shiyuexw** [comment]
谢谢提醒，已做相应的更新。

**Comment by shiyuexw** [comment]
已更新，关闭该issue
